/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AAvalieComando extends PComando
{
    private TAvalie _avalie_;
    private TAbreparentese _abreparentese_;
    private PExp _exp_;
    private TFechaparentese _fechaparentese_;
    private PCasoValorLista _casoValorLista_;
    private PSenaoDoispontos _senaoDoispontos_;
    private TFimavalie _fimavalie_;
    private TPontovirgula _pontovirgula_;

    public AAvalieComando()
    {
        // Constructor
    }

    public AAvalieComando(
        @SuppressWarnings("hiding") TAvalie _avalie_,
        @SuppressWarnings("hiding") TAbreparentese _abreparentese_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TFechaparentese _fechaparentese_,
        @SuppressWarnings("hiding") PCasoValorLista _casoValorLista_,
        @SuppressWarnings("hiding") PSenaoDoispontos _senaoDoispontos_,
        @SuppressWarnings("hiding") TFimavalie _fimavalie_,
        @SuppressWarnings("hiding") TPontovirgula _pontovirgula_)
    {
        // Constructor
        setAvalie(_avalie_);

        setAbreparentese(_abreparentese_);

        setExp(_exp_);

        setFechaparentese(_fechaparentese_);

        setCasoValorLista(_casoValorLista_);

        setSenaoDoispontos(_senaoDoispontos_);

        setFimavalie(_fimavalie_);

        setPontovirgula(_pontovirgula_);

    }

    @Override
    public Object clone()
    {
        return new AAvalieComando(
            cloneNode(this._avalie_),
            cloneNode(this._abreparentese_),
            cloneNode(this._exp_),
            cloneNode(this._fechaparentese_),
            cloneNode(this._casoValorLista_),
            cloneNode(this._senaoDoispontos_),
            cloneNode(this._fimavalie_),
            cloneNode(this._pontovirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAvalieComando(this);
    }

    public TAvalie getAvalie()
    {
        return this._avalie_;
    }

    public void setAvalie(TAvalie node)
    {
        if(this._avalie_ != null)
        {
            this._avalie_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._avalie_ = node;
    }

    public TAbreparentese getAbreparentese()
    {
        return this._abreparentese_;
    }

    public void setAbreparentese(TAbreparentese node)
    {
        if(this._abreparentese_ != null)
        {
            this._abreparentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreparentese_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TFechaparentese getFechaparentese()
    {
        return this._fechaparentese_;
    }

    public void setFechaparentese(TFechaparentese node)
    {
        if(this._fechaparentese_ != null)
        {
            this._fechaparentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaparentese_ = node;
    }

    public PCasoValorLista getCasoValorLista()
    {
        return this._casoValorLista_;
    }

    public void setCasoValorLista(PCasoValorLista node)
    {
        if(this._casoValorLista_ != null)
        {
            this._casoValorLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._casoValorLista_ = node;
    }

    public PSenaoDoispontos getSenaoDoispontos()
    {
        return this._senaoDoispontos_;
    }

    public void setSenaoDoispontos(PSenaoDoispontos node)
    {
        if(this._senaoDoispontos_ != null)
        {
            this._senaoDoispontos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senaoDoispontos_ = node;
    }

    public TFimavalie getFimavalie()
    {
        return this._fimavalie_;
    }

    public void setFimavalie(TFimavalie node)
    {
        if(this._fimavalie_ != null)
        {
            this._fimavalie_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fimavalie_ = node;
    }

    public TPontovirgula getPontovirgula()
    {
        return this._pontovirgula_;
    }

    public void setPontovirgula(TPontovirgula node)
    {
        if(this._pontovirgula_ != null)
        {
            this._pontovirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontovirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._avalie_)
            + toString(this._abreparentese_)
            + toString(this._exp_)
            + toString(this._fechaparentese_)
            + toString(this._casoValorLista_)
            + toString(this._senaoDoispontos_)
            + toString(this._fimavalie_)
            + toString(this._pontovirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._avalie_ == child)
        {
            this._avalie_ = null;
            return;
        }

        if(this._abreparentese_ == child)
        {
            this._abreparentese_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._fechaparentese_ == child)
        {
            this._fechaparentese_ = null;
            return;
        }

        if(this._casoValorLista_ == child)
        {
            this._casoValorLista_ = null;
            return;
        }

        if(this._senaoDoispontos_ == child)
        {
            this._senaoDoispontos_ = null;
            return;
        }

        if(this._fimavalie_ == child)
        {
            this._fimavalie_ = null;
            return;
        }

        if(this._pontovirgula_ == child)
        {
            this._pontovirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._avalie_ == oldChild)
        {
            setAvalie((TAvalie) newChild);
            return;
        }

        if(this._abreparentese_ == oldChild)
        {
            setAbreparentese((TAbreparentese) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._fechaparentese_ == oldChild)
        {
            setFechaparentese((TFechaparentese) newChild);
            return;
        }

        if(this._casoValorLista_ == oldChild)
        {
            setCasoValorLista((PCasoValorLista) newChild);
            return;
        }

        if(this._senaoDoispontos_ == oldChild)
        {
            setSenaoDoispontos((PSenaoDoispontos) newChild);
            return;
        }

        if(this._fimavalie_ == oldChild)
        {
            setFimavalie((TFimavalie) newChild);
            return;
        }

        if(this._pontovirgula_ == oldChild)
        {
            setPontovirgula((TPontovirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
