/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExp extends PExp
{
    private PLogicaOu _logicaOu_;

    public AExp()
    {
        // Constructor
    }

    public AExp(
        @SuppressWarnings("hiding") PLogicaOu _logicaOu_)
    {
        // Constructor
        setLogicaOu(_logicaOu_);

    }

    @Override
    public Object clone()
    {
        return new AExp(
            cloneNode(this._logicaOu_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExp(this);
    }

    public PLogicaOu getLogicaOu()
    {
        return this._logicaOu_;
    }

    public void setLogicaOu(PLogicaOu node)
    {
        if(this._logicaOu_ != null)
        {
            this._logicaOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicaOu_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicaOu_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicaOu_ == child)
        {
            this._logicaOu_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicaOu_ == oldChild)
        {
            setLogicaOu((PLogicaOu) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
