/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ALogELogicaE extends PLogicaE
{
    private PLogicaE _logicaE_;
    private TE _e_;
    private PLogicaIgualdade _logicaIgualdade_;

    public ALogELogicaE()
    {
        // Constructor
    }

    public ALogELogicaE(
        @SuppressWarnings("hiding") PLogicaE _logicaE_,
        @SuppressWarnings("hiding") TE _e_,
        @SuppressWarnings("hiding") PLogicaIgualdade _logicaIgualdade_)
    {
        // Constructor
        setLogicaE(_logicaE_);

        setE(_e_);

        setLogicaIgualdade(_logicaIgualdade_);

    }

    @Override
    public Object clone()
    {
        return new ALogELogicaE(
            cloneNode(this._logicaE_),
            cloneNode(this._e_),
            cloneNode(this._logicaIgualdade_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogELogicaE(this);
    }

    public PLogicaE getLogicaE()
    {
        return this._logicaE_;
    }

    public void setLogicaE(PLogicaE node)
    {
        if(this._logicaE_ != null)
        {
            this._logicaE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicaE_ = node;
    }

    public TE getE()
    {
        return this._e_;
    }

    public void setE(TE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public PLogicaIgualdade getLogicaIgualdade()
    {
        return this._logicaIgualdade_;
    }

    public void setLogicaIgualdade(PLogicaIgualdade node)
    {
        if(this._logicaIgualdade_ != null)
        {
            this._logicaIgualdade_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicaIgualdade_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicaE_)
            + toString(this._e_)
            + toString(this._logicaIgualdade_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicaE_ == child)
        {
            this._logicaE_ = null;
            return;
        }

        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._logicaIgualdade_ == child)
        {
            this._logicaIgualdade_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicaE_ == oldChild)
        {
            setLogicaE((PLogicaE) newChild);
            return;
        }

        if(this._e_ == oldChild)
        {
            setE((TE) newChild);
            return;
        }

        if(this._logicaIgualdade_ == oldChild)
        {
            setLogicaIgualdade((PLogicaIgualdade) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
