/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ALogIgualdadeLogicaE extends PLogicaE
{
    private PLogicaIgualdade _logicaIgualdade_;

    public ALogIgualdadeLogicaE()
    {
        // Constructor
    }

    public ALogIgualdadeLogicaE(
        @SuppressWarnings("hiding") PLogicaIgualdade _logicaIgualdade_)
    {
        // Constructor
        setLogicaIgualdade(_logicaIgualdade_);

    }

    @Override
    public Object clone()
    {
        return new ALogIgualdadeLogicaE(
            cloneNode(this._logicaIgualdade_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogIgualdadeLogicaE(this);
    }

    public PLogicaIgualdade getLogicaIgualdade()
    {
        return this._logicaIgualdade_;
    }

    public void setLogicaIgualdade(PLogicaIgualdade node)
    {
        if(this._logicaIgualdade_ != null)
        {
            this._logicaIgualdade_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicaIgualdade_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicaIgualdade_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicaIgualdade_ == child)
        {
            this._logicaIgualdade_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicaIgualdade_ == oldChild)
        {
            setLogicaIgualdade((PLogicaIgualdade) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
