/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ALogmaiorLogicaIgualdade extends PLogicaIgualdade
{
    private PLogicaMaior _logicaMaior_;

    public ALogmaiorLogicaIgualdade()
    {
        // Constructor
    }

    public ALogmaiorLogicaIgualdade(
        @SuppressWarnings("hiding") PLogicaMaior _logicaMaior_)
    {
        // Constructor
        setLogicaMaior(_logicaMaior_);

    }

    @Override
    public Object clone()
    {
        return new ALogmaiorLogicaIgualdade(
            cloneNode(this._logicaMaior_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogmaiorLogicaIgualdade(this);
    }

    public PLogicaMaior getLogicaMaior()
    {
        return this._logicaMaior_;
    }

    public void setLogicaMaior(PLogicaMaior node)
    {
        if(this._logicaMaior_ != null)
        {
            this._logicaMaior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicaMaior_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicaMaior_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicaMaior_ == child)
        {
            this._logicaMaior_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicaMaior_ == oldChild)
        {
            setLogicaMaior((PLogicaMaior) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
