/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ALogmaiorLogicaMaior extends PLogicaMaior
{
    private PLogicaMaior _logicaMaior_;
    private PRelacionalMaior _relacionalMaior_;
    private PLogicaMenor _logicaMenor_;

    public ALogmaiorLogicaMaior()
    {
        // Constructor
    }

    public ALogmaiorLogicaMaior(
        @SuppressWarnings("hiding") PLogicaMaior _logicaMaior_,
        @SuppressWarnings("hiding") PRelacionalMaior _relacionalMaior_,
        @SuppressWarnings("hiding") PLogicaMenor _logicaMenor_)
    {
        // Constructor
        setLogicaMaior(_logicaMaior_);

        setRelacionalMaior(_relacionalMaior_);

        setLogicaMenor(_logicaMenor_);

    }

    @Override
    public Object clone()
    {
        return new ALogmaiorLogicaMaior(
            cloneNode(this._logicaMaior_),
            cloneNode(this._relacionalMaior_),
            cloneNode(this._logicaMenor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogmaiorLogicaMaior(this);
    }

    public PLogicaMaior getLogicaMaior()
    {
        return this._logicaMaior_;
    }

    public void setLogicaMaior(PLogicaMaior node)
    {
        if(this._logicaMaior_ != null)
        {
            this._logicaMaior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicaMaior_ = node;
    }

    public PRelacionalMaior getRelacionalMaior()
    {
        return this._relacionalMaior_;
    }

    public void setRelacionalMaior(PRelacionalMaior node)
    {
        if(this._relacionalMaior_ != null)
        {
            this._relacionalMaior_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relacionalMaior_ = node;
    }

    public PLogicaMenor getLogicaMenor()
    {
        return this._logicaMenor_;
    }

    public void setLogicaMenor(PLogicaMenor node)
    {
        if(this._logicaMenor_ != null)
        {
            this._logicaMenor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicaMenor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicaMaior_)
            + toString(this._relacionalMaior_)
            + toString(this._logicaMenor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicaMaior_ == child)
        {
            this._logicaMaior_ = null;
            return;
        }

        if(this._relacionalMaior_ == child)
        {
            this._relacionalMaior_ = null;
            return;
        }

        if(this._logicaMenor_ == child)
        {
            this._logicaMenor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicaMaior_ == oldChild)
        {
            setLogicaMaior((PLogicaMaior) newChild);
            return;
        }

        if(this._relacionalMaior_ == oldChild)
        {
            setRelacionalMaior((PRelacionalMaior) newChild);
            return;
        }

        if(this._logicaMenor_ == oldChild)
        {
            setLogicaMenor((PLogicaMenor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
