/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ALogXorLogicaOu extends PLogicaOu
{
    private PLogicaXor _logicaXor_;

    public ALogXorLogicaOu()
    {
        // Constructor
    }

    public ALogXorLogicaOu(
        @SuppressWarnings("hiding") PLogicaXor _logicaXor_)
    {
        // Constructor
        setLogicaXor(_logicaXor_);

    }

    @Override
    public Object clone()
    {
        return new ALogXorLogicaOu(
            cloneNode(this._logicaXor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogXorLogicaOu(this);
    }

    public PLogicaXor getLogicaXor()
    {
        return this._logicaXor_;
    }

    public void setLogicaXor(PLogicaXor node)
    {
        if(this._logicaXor_ != null)
        {
            this._logicaXor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicaXor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicaXor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicaXor_ == child)
        {
            this._logicaXor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicaXor_ == oldChild)
        {
            setLogicaXor((PLogicaXor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
