/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ALogmenorLogicaMaior extends PLogicaMaior
{
    private PLogicaMenor _logicaMenor_;

    public ALogmenorLogicaMaior()
    {
        // Constructor
    }

    public ALogmenorLogicaMaior(
        @SuppressWarnings("hiding") PLogicaMenor _logicaMenor_)
    {
        // Constructor
        setLogicaMenor(_logicaMenor_);

    }

    @Override
    public Object clone()
    {
        return new ALogmenorLogicaMaior(
            cloneNode(this._logicaMenor_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogmenorLogicaMaior(this);
    }

    public PLogicaMenor getLogicaMenor()
    {
        return this._logicaMenor_;
    }

    public void setLogicaMenor(PLogicaMenor node)
    {
        if(this._logicaMenor_ != null)
        {
            this._logicaMenor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicaMenor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicaMenor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicaMenor_ == child)
        {
            this._logicaMenor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicaMenor_ == oldChild)
        {
            setLogicaMenor((PLogicaMenor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
