/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ALogELogicaXor extends PLogicaXor
{
    private PLogicaE _logicaE_;

    public ALogELogicaXor()
    {
        // Constructor
    }

    public ALogELogicaXor(
        @SuppressWarnings("hiding") PLogicaE _logicaE_)
    {
        // Constructor
        setLogicaE(_logicaE_);

    }

    @Override
    public Object clone()
    {
        return new ALogELogicaXor(
            cloneNode(this._logicaE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogELogicaXor(this);
    }

    public PLogicaE getLogicaE()
    {
        return this._logicaE_;
    }

    public void setLogicaE(PLogicaE node)
    {
        if(this._logicaE_ != null)
        {
            this._logicaE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicaE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicaE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicaE_ == child)
        {
            this._logicaE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicaE_ == oldChild)
        {
            setLogicaE((PLogicaE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
