/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ALogmenorLogicaMenor extends PLogicaMenor
{
    private PLogicaMenor _logicaMenor_;
    private PRelacionalMenor _relacionalMenor_;
    private PSomaExp _somaExp_;

    public ALogmenorLogicaMenor()
    {
        // Constructor
    }

    public ALogmenorLogicaMenor(
        @SuppressWarnings("hiding") PLogicaMenor _logicaMenor_,
        @SuppressWarnings("hiding") PRelacionalMenor _relacionalMenor_,
        @SuppressWarnings("hiding") PSomaExp _somaExp_)
    {
        // Constructor
        setLogicaMenor(_logicaMenor_);

        setRelacionalMenor(_relacionalMenor_);

        setSomaExp(_somaExp_);

    }

    @Override
    public Object clone()
    {
        return new ALogmenorLogicaMenor(
            cloneNode(this._logicaMenor_),
            cloneNode(this._relacionalMenor_),
            cloneNode(this._somaExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALogmenorLogicaMenor(this);
    }

    public PLogicaMenor getLogicaMenor()
    {
        return this._logicaMenor_;
    }

    public void setLogicaMenor(PLogicaMenor node)
    {
        if(this._logicaMenor_ != null)
        {
            this._logicaMenor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._logicaMenor_ = node;
    }

    public PRelacionalMenor getRelacionalMenor()
    {
        return this._relacionalMenor_;
    }

    public void setRelacionalMenor(PRelacionalMenor node)
    {
        if(this._relacionalMenor_ != null)
        {
            this._relacionalMenor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relacionalMenor_ = node;
    }

    public PSomaExp getSomaExp()
    {
        return this._somaExp_;
    }

    public void setSomaExp(PSomaExp node)
    {
        if(this._somaExp_ != null)
        {
            this._somaExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._somaExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._logicaMenor_)
            + toString(this._relacionalMenor_)
            + toString(this._somaExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._logicaMenor_ == child)
        {
            this._logicaMenor_ = null;
            return;
        }

        if(this._relacionalMenor_ == child)
        {
            this._relacionalMenor_ = null;
            return;
        }

        if(this._somaExp_ == child)
        {
            this._somaExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._logicaMenor_ == oldChild)
        {
            setLogicaMenor((PLogicaMenor) newChild);
            return;
        }

        if(this._relacionalMenor_ == oldChild)
        {
            setRelacionalMenor((PRelacionalMenor) newChild);
            return;
        }

        if(this._somaExp_ == oldChild)
        {
            setSomaExp((PSomaExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
