/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ANegNegar extends PNegar
{
    private TNegacao _negacao_;
    private PNegar _negar_;

    public ANegNegar()
    {
        // Constructor
    }

    public ANegNegar(
        @SuppressWarnings("hiding") TNegacao _negacao_,
        @SuppressWarnings("hiding") PNegar _negar_)
    {
        // Constructor
        setNegacao(_negacao_);

        setNegar(_negar_);

    }

    @Override
    public Object clone()
    {
        return new ANegNegar(
            cloneNode(this._negacao_),
            cloneNode(this._negar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegNegar(this);
    }

    public TNegacao getNegacao()
    {
        return this._negacao_;
    }

    public void setNegacao(TNegacao node)
    {
        if(this._negacao_ != null)
        {
            this._negacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._negacao_ = node;
    }

    public PNegar getNegar()
    {
        return this._negar_;
    }

    public void setNegar(PNegar node)
    {
        if(this._negar_ != null)
        {
            this._negar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._negar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._negacao_)
            + toString(this._negar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._negacao_ == child)
        {
            this._negacao_ = null;
            return;
        }

        if(this._negar_ == child)
        {
            this._negar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._negacao_ == oldChild)
        {
            setNegacao((TNegacao) newChild);
            return;
        }

        if(this._negar_ == oldChild)
        {
            setNegar((PNegar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
