/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AProxTermo extends PTermo
{
    private PNegar _negar_;

    public AProxTermo()
    {
        // Constructor
    }

    public AProxTermo(
        @SuppressWarnings("hiding") PNegar _negar_)
    {
        // Constructor
        setNegar(_negar_);

    }

    @Override
    public Object clone()
    {
        return new AProxTermo(
            cloneNode(this._negar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAProxTermo(this);
    }

    public PNegar getNegar()
    {
        return this._negar_;
    }

    public void setNegar(PNegar node)
    {
        if(this._negar_ != null)
        {
            this._negar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._negar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._negar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._negar_ == child)
        {
            this._negar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._negar_ == oldChild)
        {
            setNegar((PNegar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
