/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class APrograma extends PPrograma
{
    private PProgramaInicio _programaInicio_;
    private PDeclaracaoLista _declaracaoLista_;
    private PComandoLista _comandoLista_;
    private TFimPrograma _fimPrograma_;

    public APrograma()
    {
        // Constructor
    }

    public APrograma(
        @SuppressWarnings("hiding") PProgramaInicio _programaInicio_,
        @SuppressWarnings("hiding") PDeclaracaoLista _declaracaoLista_,
        @SuppressWarnings("hiding") PComandoLista _comandoLista_,
        @SuppressWarnings("hiding") TFimPrograma _fimPrograma_)
    {
        // Constructor
        setProgramaInicio(_programaInicio_);

        setDeclaracaoLista(_declaracaoLista_);

        setComandoLista(_comandoLista_);

        setFimPrograma(_fimPrograma_);

    }

    @Override
    public Object clone()
    {
        return new APrograma(
            cloneNode(this._programaInicio_),
            cloneNode(this._declaracaoLista_),
            cloneNode(this._comandoLista_),
            cloneNode(this._fimPrograma_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAPrograma(this);
    }

    public PProgramaInicio getProgramaInicio()
    {
        return this._programaInicio_;
    }

    public void setProgramaInicio(PProgramaInicio node)
    {
        if(this._programaInicio_ != null)
        {
            this._programaInicio_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._programaInicio_ = node;
    }

    public PDeclaracaoLista getDeclaracaoLista()
    {
        return this._declaracaoLista_;
    }

    public void setDeclaracaoLista(PDeclaracaoLista node)
    {
        if(this._declaracaoLista_ != null)
        {
            this._declaracaoLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declaracaoLista_ = node;
    }

    public PComandoLista getComandoLista()
    {
        return this._comandoLista_;
    }

    public void setComandoLista(PComandoLista node)
    {
        if(this._comandoLista_ != null)
        {
            this._comandoLista_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoLista_ = node;
    }

    public TFimPrograma getFimPrograma()
    {
        return this._fimPrograma_;
    }

    public void setFimPrograma(TFimPrograma node)
    {
        if(this._fimPrograma_ != null)
        {
            this._fimPrograma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fimPrograma_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._programaInicio_)
            + toString(this._declaracaoLista_)
            + toString(this._comandoLista_)
            + toString(this._fimPrograma_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._programaInicio_ == child)
        {
            this._programaInicio_ = null;
            return;
        }

        if(this._declaracaoLista_ == child)
        {
            this._declaracaoLista_ = null;
            return;
        }

        if(this._comandoLista_ == child)
        {
            this._comandoLista_ = null;
            return;
        }

        if(this._fimPrograma_ == child)
        {
            this._fimPrograma_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._programaInicio_ == oldChild)
        {
            setProgramaInicio((PProgramaInicio) newChild);
            return;
        }

        if(this._declaracaoLista_ == oldChild)
        {
            setDeclaracaoLista((PDeclaracaoLista) newChild);
            return;
        }

        if(this._comandoLista_ == oldChild)
        {
            setComandoLista((PComandoLista) newChild);
            return;
        }

        if(this._fimPrograma_ == oldChild)
        {
            setFimPrograma((TFimPrograma) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
