/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ASeComando extends PComando
{
    private TSe _se_;
    private TAbreparentese _abreparentese_;
    private PExpLogica _expLogica_;
    private TFechaparentese _fechaparentese_;
    private TEntao _entao_;
    private PComandoPvirgulaOp _comandoPvirgulaOp_;
    private PComandoPvirgula _comandoPvirgula_;
    private PSenaoOpcional _senaoOpcional_;
    private TFimse _fimse_;
    private TPontovirgula _pontovirgula_;

    public ASeComando()
    {
        // Constructor
    }

    public ASeComando(
        @SuppressWarnings("hiding") TSe _se_,
        @SuppressWarnings("hiding") TAbreparentese _abreparentese_,
        @SuppressWarnings("hiding") PExpLogica _expLogica_,
        @SuppressWarnings("hiding") TFechaparentese _fechaparentese_,
        @SuppressWarnings("hiding") TEntao _entao_,
        @SuppressWarnings("hiding") PComandoPvirgulaOp _comandoPvirgulaOp_,
        @SuppressWarnings("hiding") PComandoPvirgula _comandoPvirgula_,
        @SuppressWarnings("hiding") PSenaoOpcional _senaoOpcional_,
        @SuppressWarnings("hiding") TFimse _fimse_,
        @SuppressWarnings("hiding") TPontovirgula _pontovirgula_)
    {
        // Constructor
        setSe(_se_);

        setAbreparentese(_abreparentese_);

        setExpLogica(_expLogica_);

        setFechaparentese(_fechaparentese_);

        setEntao(_entao_);

        setComandoPvirgulaOp(_comandoPvirgulaOp_);

        setComandoPvirgula(_comandoPvirgula_);

        setSenaoOpcional(_senaoOpcional_);

        setFimse(_fimse_);

        setPontovirgula(_pontovirgula_);

    }

    @Override
    public Object clone()
    {
        return new ASeComando(
            cloneNode(this._se_),
            cloneNode(this._abreparentese_),
            cloneNode(this._expLogica_),
            cloneNode(this._fechaparentese_),
            cloneNode(this._entao_),
            cloneNode(this._comandoPvirgulaOp_),
            cloneNode(this._comandoPvirgula_),
            cloneNode(this._senaoOpcional_),
            cloneNode(this._fimse_),
            cloneNode(this._pontovirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASeComando(this);
    }

    public TSe getSe()
    {
        return this._se_;
    }

    public void setSe(TSe node)
    {
        if(this._se_ != null)
        {
            this._se_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._se_ = node;
    }

    public TAbreparentese getAbreparentese()
    {
        return this._abreparentese_;
    }

    public void setAbreparentese(TAbreparentese node)
    {
        if(this._abreparentese_ != null)
        {
            this._abreparentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._abreparentese_ = node;
    }

    public PExpLogica getExpLogica()
    {
        return this._expLogica_;
    }

    public void setExpLogica(PExpLogica node)
    {
        if(this._expLogica_ != null)
        {
            this._expLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expLogica_ = node;
    }

    public TFechaparentese getFechaparentese()
    {
        return this._fechaparentese_;
    }

    public void setFechaparentese(TFechaparentese node)
    {
        if(this._fechaparentese_ != null)
        {
            this._fechaparentese_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fechaparentese_ = node;
    }

    public TEntao getEntao()
    {
        return this._entao_;
    }

    public void setEntao(TEntao node)
    {
        if(this._entao_ != null)
        {
            this._entao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._entao_ = node;
    }

    public PComandoPvirgulaOp getComandoPvirgulaOp()
    {
        return this._comandoPvirgulaOp_;
    }

    public void setComandoPvirgulaOp(PComandoPvirgulaOp node)
    {
        if(this._comandoPvirgulaOp_ != null)
        {
            this._comandoPvirgulaOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoPvirgulaOp_ = node;
    }

    public PComandoPvirgula getComandoPvirgula()
    {
        return this._comandoPvirgula_;
    }

    public void setComandoPvirgula(PComandoPvirgula node)
    {
        if(this._comandoPvirgula_ != null)
        {
            this._comandoPvirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoPvirgula_ = node;
    }

    public PSenaoOpcional getSenaoOpcional()
    {
        return this._senaoOpcional_;
    }

    public void setSenaoOpcional(PSenaoOpcional node)
    {
        if(this._senaoOpcional_ != null)
        {
            this._senaoOpcional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senaoOpcional_ = node;
    }

    public TFimse getFimse()
    {
        return this._fimse_;
    }

    public void setFimse(TFimse node)
    {
        if(this._fimse_ != null)
        {
            this._fimse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fimse_ = node;
    }

    public TPontovirgula getPontovirgula()
    {
        return this._pontovirgula_;
    }

    public void setPontovirgula(TPontovirgula node)
    {
        if(this._pontovirgula_ != null)
        {
            this._pontovirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontovirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._se_)
            + toString(this._abreparentese_)
            + toString(this._expLogica_)
            + toString(this._fechaparentese_)
            + toString(this._entao_)
            + toString(this._comandoPvirgulaOp_)
            + toString(this._comandoPvirgula_)
            + toString(this._senaoOpcional_)
            + toString(this._fimse_)
            + toString(this._pontovirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._se_ == child)
        {
            this._se_ = null;
            return;
        }

        if(this._abreparentese_ == child)
        {
            this._abreparentese_ = null;
            return;
        }

        if(this._expLogica_ == child)
        {
            this._expLogica_ = null;
            return;
        }

        if(this._fechaparentese_ == child)
        {
            this._fechaparentese_ = null;
            return;
        }

        if(this._entao_ == child)
        {
            this._entao_ = null;
            return;
        }

        if(this._comandoPvirgulaOp_ == child)
        {
            this._comandoPvirgulaOp_ = null;
            return;
        }

        if(this._comandoPvirgula_ == child)
        {
            this._comandoPvirgula_ = null;
            return;
        }

        if(this._senaoOpcional_ == child)
        {
            this._senaoOpcional_ = null;
            return;
        }

        if(this._fimse_ == child)
        {
            this._fimse_ = null;
            return;
        }

        if(this._pontovirgula_ == child)
        {
            this._pontovirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._se_ == oldChild)
        {
            setSe((TSe) newChild);
            return;
        }

        if(this._abreparentese_ == oldChild)
        {
            setAbreparentese((TAbreparentese) newChild);
            return;
        }

        if(this._expLogica_ == oldChild)
        {
            setExpLogica((PExpLogica) newChild);
            return;
        }

        if(this._fechaparentese_ == oldChild)
        {
            setFechaparentese((TFechaparentese) newChild);
            return;
        }

        if(this._entao_ == oldChild)
        {
            setEntao((TEntao) newChild);
            return;
        }

        if(this._comandoPvirgulaOp_ == oldChild)
        {
            setComandoPvirgulaOp((PComandoPvirgulaOp) newChild);
            return;
        }

        if(this._comandoPvirgula_ == oldChild)
        {
            setComandoPvirgula((PComandoPvirgula) newChild);
            return;
        }

        if(this._senaoOpcional_ == oldChild)
        {
            setSenaoOpcional((PSenaoOpcional) newChild);
            return;
        }

        if(this._fimse_ == oldChild)
        {
            setFimse((TFimse) newChild);
            return;
        }

        if(this._pontovirgula_ == oldChild)
        {
            setPontovirgula((TPontovirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
