/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class TFimenquanto extends Token
{
    public TFimenquanto()
    {
        super.setText("fimenquanto");
    }

    public TFimenquanto(int line, int pos)
    {
        super.setText("fimenquanto");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TFimenquanto(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTFimenquanto(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TFimenquanto text.");
    }
}
